<?php
	// use PHPMailer\PHPMailer\PHPMailer;
	// use PHPMailer\PHPMailer\SMTP;
	// use PHPMailer\PHPMailer\Exception;

    require_once "PHPMailer/PHPMailer.php";
    require_once "PHPMailer/SMTP.php";
	if (isset($_POST['submit'])) {
    // Get data from form  
    $name = $_POST['name'];
    $email= $_POST['email'];
    $message= $_POST['message'];
    
    require 'vendor/autoload.php';

    //$mail = new PHPMailer(true);  
    $mail = new PHPMailer\PHPMailer\PHPMailer();
        
    $mail->SMTPDebug = PHPMailer\PHPMailer\SMTP::DEBUG_SERVER;
    $mail->isSMTP();
    $mail->Host = 'smtp.gmail.com';
    $mail->SMTPAuth = true;
    $mail->Username = 'elyaquino53@gmail.com';
    $mail->Password = 'xhouetqkfrgmdtmd';
    $mail->SMTPSecure = PHPMailer\PHPMailer\PHPMailer::ENCRYPTION_SMTPS;
    $mail->Port = 465;

    //$mail->setFrom("elyaquino53@gmail.com", 'Barangay San Vicente, Sta Maria, Bulacan');
    $mail->setFrom("$email");
    $mail->addAddress("elyaquino53@gmail.com", 'Barangay San Vicente, Sta Maria, Bulacan');
    //$mail->addAddress($email);

    $mail->isHTML(true);
    $mail->Subject = 'Welcome to Barangay San Vicente, Sta Maria, Bulacan 1st Portal - Feedback/Survey';
    $mail->Body = "Good day Barangay!<br><br>
    We strive to provide the highest quality service and care deeply about how our work affects resident like you.<br>
    We would love it if you could send us an email and tell us what we can do to make Barangay San Vicente, Sta Maria, Bulacan better..<br><br>
    Thank you for taking the time out of your day. We really appreciate it!<br>
    <h3>From Name: $name / Email: $email</h3><br>
    <h3>Message: $message </h3><br>
    
    Note – This is a system autogenerated reply <br><br>
    Best Regards, <br>
    Barangay San Vicente";
    
    if ($mail->send()) {
        echo "<script>alert('Resident sent a feedback/survey. Message sent to email!');window.open('feedback', '_self')</script>";
    } 

    else {
        echo $mail->ErrorInfo;
    }
}
    
?>