<?php

	ob_start(); 
	session_start(); 
	include('../global/model.php');
	$model = new Model();
	include('department.php');

	// if (empty($_SESSION['sess'])) {
	// 	echo "<script>window.open('../','_self');</script>";
	// }
	// require "PHPMailer/PHPMailer.php";
	// require "PHPMailer/SMTP.php";
	// require "PHPMailer/Exception.php";

	// if (isset($_POST['submit'])) {
	// 	require 'vendor/autoload.php';
	// 	$mail = new PHPMailer(true);
			
	// 	$name = $_POST['name'];
	// 	$email= $_POST['email'];
	// 	$message= $_POST['message'];

	// 	$mail->SMTPDebug = SMTP::DEBUG_SERVER;
	// 	$mail->isSMTP();
	// 	$mail->Host = 'smtp.gmail.com';
	// 	$mail->SMTPAuth = true;
	// 	$mail->Username = 'elyaquino53@gmail.com';
	// 	$mail->Password = 'xhouetqkfrgmdtmd';
	// 	$mail->SMTPSecure = PHPMailer::ENCRYPTION_SMTPS;
	// 	$mail->Port = 465;
	
	// 	$mail->setFrom("elyaquino53@gmail.com", 'Barangay San Vicente, Sta Maria, Bulacan');
	// 	$mail->addAddress($email);
	
	// 	$mail->isHTML(true);
	// 	$mail->Subject = 'Welcome to Barangay San Vicente, Sta Maria, Bulacan 1st Portal - Feedback/Survey';
	// 	$mail->Body = "Good day Resident!<br><br>
	// 	We strive to provide the highest quality service and care deeply about how our work affects resident like you.<br>
	// 	We would love it if you could send us an email and tell us what we can do to make Barangay San Vicente, Sta Maria, Bulacan better..<br><br>
	// 	Thank you for taking the time out of your day. We really appreciate it!<br>
	// 	<h2>Email: $email </h2><br>
	// 	<h3>Message: $message </h3><br>
		
	// 	Note – This is a system autogenerated reply <br><br>
	// 	Best Regards, <br>
	// 	Barangay San Vicente";
		
	// 	if ($mail->send()) {
	// 		echo "<script>alert('Resident has been added. Password has been sent to email!');window.open('residents', '_self')</script>";
	// 	} 
	
	// 	else {
	// 		echo $mail->ErrorInfo;
	// 	}
	// }

?>
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="keywords" content="" />
		<meta name="author" content="" />
		<meta name="robots" content="" />

		<meta name="description" content="" />

		<meta property="og:title" content="" />
		<meta property="og:description" content="" />
		<meta property="og:image" content="" />
		<meta name="format-detection" content="telephone=no">

		<link rel="icon" href="../assets/images/<?php echo $web_icon; ?>.png" type="image/x-icon" />
		<link rel="shortcut icon" type="image/x-icon" href="../assets/images/<?php echo $web_icon; ?>.png" />

		<title><?php echo $web_name; ?></title>

		<meta name="viewport" content="width=device-width, initial-scale=1">

		<link rel="stylesheet" type="text/css" href="../dashboard/assets/css/dataTables.bootstrap4.min.css">
		<link rel="stylesheet" type="text/css" href="../dashboard/assets/css/assets.css">
		<link rel="stylesheet" type="text/css" href="../dashboard/assets/vendors/calendar/fullcalendar.css">

		<link rel="stylesheet" type="text/css" href="../dashboard/assets/css/typography.css">

		<link rel="stylesheet" type="text/css" href="../dashboard/assets/css/shortcodes/shortcodes.css">

		<link rel="stylesheet" type="text/css" href="../dashboard/assets/css/style.css">
		<link rel="stylesheet" type="text/css" href="../dashboard/assets/css/dashboard.css">

		<style type="text/css">
			.btn.dropdown-toggle.btn-default:hover {
				color: #000!important;
			}

			.btn.dropdown-toggle.btn-default:focus {
				color: #000!important;
			}
			.widget-card .icon {
				position: absolute;
				top: auto;
				bottom: -20px;
				right: 5px;
				z-index: 0;
				font-size: 65px;
				color: rgba(0, 0, 0, 0.15);
			}
			tbody tr:hover {
				background-color: #d4d4d4;
			}
            .absolute1 {
            width: 150px;
            background-color: #ffd7c2;
            position: absolute;
            right: 30px;
            }
		</style>
	</head>
	<?php include '../assets/css/color/color-1.php';  ?>
	<body class="ttr-opened-sidebar ttr-pinned-sidebar" style="background-color: #FCFCFC;">

		<?php include 'navbar.php'; ?>

		<div class="ttr-sidebar">
			<div class="ttr-sidebar-wrapper content-scroll">
				
				<?php 
			
				include 'sidebar.php';
				
				$page = 'feedback';
				$secondnav = '';

				include 'nav.php'; 

				?>

				
			</div>
		</div>
		<main class="ttr-wrapper" style="background-color: #FCFCFC;">
			<div class="container-fluid">
				<div class="db-breadcrumb">
					<h4 class="breadcrumb-title">Feedback/ Survey</h4>
					<ul class="db-breadcrumb-list">
						<li><i class="ti-user"></i>Profiles</li>
					</ul>
				</div> 
				
				<?php include 'widget.php'; ?>

				<div class="row">
					<div class="col-lg-12 m-b30">
                    <div class="full">
                    <h3>Drop a Message</h3>
 
                    <div class="lt">
 
                    <!-- form starting  -->
                    <form class="form-horizontal" method="POST" action="emailsend.php">
                        <div class="form-group">
                            <div class="col-sm-12">
                                <!-- name  -->
                                <input type="text" class="form-control" readonly
                                    name="name" value="<?php echo $r_fname; ?> <?php echo $r_mname; ?> <?php echo $r_lname; ?>" />
                            </div>
                        </div>
    
                        <div class="form-group">
                            <div class="col-sm-12">
                                <!-- email  -->
                                <input type="email" class="form-control"
                                    readonly
                                    name="email"
                                    value="<?php echo $r_email; ?>" />
                            </div>
                        </div>
    
                        <!-- message  -->
                        <div class="form-group">
                            <div class="col-sm-12">
                                <textarea class="form-control" name="message"></textarea>
                            </div>
                        </div>
                      
                        <button class="btn btn-primary send-button absolute1 "
                                        name="submit" type="submit" value="SEND">
                                    <i class="fa fa-paper-plane"></i>
                                    <span class="send-text">SEND</span>
                        </button>
                             
                       
                    </form>
                    <!-- end of form -->
                    </div>
                    </div>
					</div>
				</div>
			</div>
		</main>
		<div class="ttr-overlay"></div>

		<script src="../dashboard/assets/js/jquery.min.js"></script>
		<script src="../dashboard/assets/vendors/bootstrap/js/popper.min.js"></script>
		<script src="../dashboard/assets/vendors/bootstrap/js/bootstrap.min.js"></script>
		<script src="../dashboard/assets/vendors/bootstrap-select/bootstrap-select.min.js"></script>
		<script src="../dashboard/assets/vendors/bootstrap-touchspin/jquery.bootstrap-touchspin.js"></script>
		<script src="../dashboard/assets/vendors/magnific-popup/magnific-popup.js"></script>
		<script src="../dashboard/assets/vendors/counter/waypoints-min.js"></script>
		<script src="../dashboard/assets/vendors/counter/counterup.min.js"></script>
		<script src="../dashboard/assets/vendors/imagesloaded/imagesloaded.js"></script>
		<script src="../dashboard/assets/vendors/masonry/masonry.js"></script>
		<script src="../dashboard/assets/vendors/masonry/filter.js"></script>
		<script src="../dashboard/assets/vendors/owl-carousel/owl.carousel.js"></script>
		<script src='../dashboard/assets/vendors/scroll/scrollbar.min.js'></script>
		<script src="../dashboard/assets/js/functions.js"></script>
		<script src="../dashboard/assets/vendors/chart/chart.min.js"></script>
		<script src="../dashboard/assets/js/admin.js"></script>
		<script src='../dashboard/assets/vendors/calendar/moment.min.js'></script>   
		<script src="../dashboard/assets/js/jquery.dataTables.min.js"></script>
		<script src="../dashboard/assets/js/dataTables.bootstrap4.min.js"></script>

		<script type="text/javascript">
			$(document).ready(function() {
				$('#table').DataTable();
			});

			$(document).ready(function(){
				$('[data-toggle="tooltip"]').tooltip();
			});
		</script>
	</body>

</html>